### ISSUE TITLE
Corrupting character in the table of contents.

### ISSUE THREAD

**Issue by kou1okada** [akira-okumura/MasterThesisTemplate#5]
In my environment (Windows 10 Pro 64 bits 1909), the characters in the table of  contents are corrupted.

Edge
![main pdf -  InPrivate  - Microsoft​ Edge 2021_02_04 12_27_59](https://user-images.githubusercontent.com/1631846/106841656-e1fe1080-66e5-11eb-9c16-572c23ff2d11.png)
Chrome
![main pdf - Google Chrome 2021_02_04 12_28_02](https://user-images.githubusercontent.com/1631846/106841679-ea564b80-66e5-11eb-88d6-7f7f36d4f2da.png)
Firefox
![main pdf — Mozilla Firefox (プライベートブラウジング) 2021_02_04 12_28_08](https://user-images.githubusercontent.com/1631846/106841700-efb39600-66e5-11eb-9374-4552d0584ddf.png)
Adobe Reader
![main pdf - Adobe Acrobat Reader DC 2021_02_04 12_28_10](https://user-images.githubusercontent.com/1631846/106841720-f6420d80-66e5-11eb-8f83-001ee42bfee8.png)

**Comment by kou1okada** [comment]
Ubuntu 18.04.5 LTS 64bits
Firefox
![Screenshot from 2021-02-04 12-50-16](https://user-images.githubusercontent.com/1631846/106842734-e9261e00-66e7-11eb-8255-4da68531cd95.png)
Evince
![Screenshot from 2021-02-04 12-55-09](https://user-images.githubusercontent.com/1631846/106842952-4cb04b80-66e8-11eb-857d-5a76282342d2.png)

**Comment by akira-okumura** [comment]
Thank you. It has been already fixed. Please see
- PR https://github.com/akira-okumura/MasterThesisTemplate/pull/4
- Commit https://github.com/akira-okumura/MasterThesisTemplate/commit/df51f87bf29dcbf0721b3b395bb6226d04ccc901

**Comment by kou1okada** [comment]
Sorry, I only checked [v.2.3.0](https://github.com/akira-okumura/MasterThesisTemplate/releases/tag/v2.3.0), but I didn't check PRs and commits.

Thank you.
